version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"